/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/scenery/cage.glb --transform 
Files: ./public/scenery/cage.glb [1.17MB] > /Users/cudisquare/development/repository/layne-chen-portfolio/cage-transformed.glb [77.6KB] (93%)
Author: riach (https://sketchfab.com/riach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-rainbow-translucent-pendant-fd730e2886e748a0bd645d05fd96040d
Title: Abstract Rainbow Translucent Pendant
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cage-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Hedra001_Material_#0_0'].geometry} material={materials.Material_0} position={[-0.016, 0, 0.088]} rotation={[-Math.PI / 2, 0, 0]} scale={0.016} />
    </group>
  )
}

useGLTF.preload('/cage-transformed.glb')
