/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/scenery/particles.glb --transform 
Files: ./public/scenery/particles.glb [6.89MB] > /Users/cudisquare/development/repository/layne-chen-portfolio/particles-transformed.glb [590.04KB] (91%)
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-cluster-15k-stars-model-51148b78a37a4a72b22d8e06f4293e07
Title: Star Cluster - 15k stars model
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/particles-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <group name="StarCluster3" scale={100}>
            <group name="Object_5" position={[-0.703, 0, 0]}>
              <mesh name="StarCluster3_03_-__0" geometry={nodes['StarCluster3_03_-__0'].geometry} material={materials['03_-']} />
            </group>
          </group>
          <group name="StarCluster2" scale={49.606}>
            <group name="Object_8" position={[-1.549, 0, 0]}>
              <mesh name="StarCluster2_02_-__0" geometry={nodes['StarCluster2_02_-__0'].geometry} material={materials['02_-']} />
            </group>
          </group>
          <group name="StarCluster1" scale={24.803}>
            <group name="Object_11" position={[-1.993, 0, 0]}>
              <mesh name="StarCluster1_01_-__0" geometry={nodes['StarCluster1_01_-__0'].geometry} material={materials['01_-']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/particles-transformed.glb')
