import type { Metadata } from 'next';
import { Inter, Krona_One } from 'next/font/google';
import { ReactLenis } from '@studio-freight/react-lenis';
import SmoothScrolling from '@/components/SmoothScroll';
import localFont from 'next/font/local';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const kronaOne = Krona_One({ weight: '400', subsets: ['latin'], variable: '--font-krona-one' });
const clashDisplay = localFont({ src: '../public/font/ClashDisplay.ttf', variable: '--font-clash-display' });
const boxing = localFont({ src: '../public/font/Boxing-Regular.woff', variable: '--font-boxing' });
const satoshi = localFont({ src: '../public/font/Satoshi-Bold.woff', variable: '--font-satoshi' });

const fonts = `${inter.variable} ${kronaOne.variable} ${clashDisplay.variable} ${boxing.variable} ${satoshi.variable}`;

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={fonts}>
			<body>
				<SmoothScrolling>{children}</SmoothScrolling>
			</body>
		</html>
	);
}
