import type { Metadata } from 'next';
import { Inter, Krona_One } from 'next/font/google';
import { ReactLenis } from '@studio-freight/react-lenis';
import SmoothScrolling from '@/components/SmoothScroll';
import localFont from 'next/font/local';

import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const kronaOne = Krona_One({ weight: '400', subsets: ['latin'], variable: '--font-krona-one' });
const clashDisplay = localFont({ src: '../public/font/ClashDisplay.ttf', variable: '--font-clash-display' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className={`${inter.variable} ${kronaOne.variable} ${clashDisplay.variable}`}>
			<body>
				<SmoothScrolling>{children}</SmoothScrolling>
				{/* {children} */}
			</body>
		</html>
	);
}
