import type { Metadata } from 'next';
import { Inter, Krona_One } from 'next/font/google';
import { ReactLenis } from '@studio-freight/react-lenis';
import SmoothScrolling from '@/components/SmoothScroll';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const kronaOne = Krona_One({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} ${kronaOne.className}`}>
				<SmoothScrolling>{children}</SmoothScrolling>
				{/* {children} */}
			</body>
		</html>
	);
}
