export const MESH_DISTANCE = {
	TEXT: 3,
	TORSO: 0,
	CONTAINER: 2.9,
	BALL: 0,
};

export const MESH_NAME = {
	TEXT_GROUP: 'TEXT_MESH_GROUP',
	CONTAINER_GROUP: 'CONTAINER_MESH_GROUP',
	TORSO: 'TORSO_MESH',
	BALL: 'BALL_MESH',
	CLONED_BALL: 'CLONE_BALL_MESH',
};
